### PR TITLE
Implement basic support for Firebase Remote Config

### PR DESCRIPTION
**Pull request by greenfield932**
Implement basic support for Firebase Remote Config 
(not tested for ios, unfortunately I have no environment to test, so linking stage may fail, probably may require project file libs section to fix). 
Example of how to use in QML code added to remote config class header file.

### CODE REVIEW

**Comment by Larpon** [comment]
Thank you very much for contributing. This is super cool!
I'll check it out ASAP - when everything is set I'll ad your example use comment to the QtFirebaseExample project when everything is set

**Comment by Larpon** [comment]
@greenfield932 - it works on my Android device as well with Firebase C++ SDK 3.1.0 - good job. Let's merge!

I think we could improve it a bit by having a low priority timer that pull/call `requestConfig` automatically?
and a property to set the timeout on said timer.

Maybe add a `parametersUpdated` signal or similar? What do you think?

**Comment by Larpon** [comment]
I'll do a house cleaning round for the deprecated Future calls as well

**Comment by greenfield932** [comment]
First of all thank you for this great plugin, I added ads and analytics in 2 days to my app, while mostly spending time on learning firebase console stuff!

Reagarding the improvements.
I'm not sure about the timer, since you need to call addParameter function first (before requestConfig). I think for the flow you are mentioned it requires to set parameters in another way, something like you did in analytics
`userProperties: [
            { "sign_up_method" : "Google" },
            { "qtfirebase_power_user" : "yes" },
            { "qtfirebase_custom_property" : "test_value" }
        ]`

My flow is pretty simple: in onReadyChanged handler initialize parameters list and start fetching them, onLoaded handler just get them. If fetching ok - onLoaded called, otherwise onError called.

So to implement it via timer I think we should change a flow a little bit.
Get rid of onLoadedChanged, onReadyChanged stuff and loaded, ready variables in QML code, add timer value parameter (probably we can also add loop count to call it once or infinite), and move retrieving of values to onParametersUpdated. onError handler keep as it was. So in case of success we call parametersUpdated, otherwise onError handler. Probably add enable variable. Is it what you are expecting?
`RemoteConfig{
    parameters: [
            { "TestString" : "test" },
            { "TestDouble" : 2.56 },
            { "TestLong" : 1100}
        ]
    onError:{
        console.log(message);
    }
    onParametersUpdated:{
        //access them via parameters variable or getParameterValue call
    }
    timeout: 100000
    loops: 1
    enabled: true
}`

**Comment by greenfield932** [comment]
Formatting broken when use code tags, repost again the QML code will look like which I propose.
RemoteConfig{
 parameters: [ 
	{ "TestString" : "test" }, 
	{ "TestDouble" : 2.56 }, 
	{ "TestLong" : 1100} ] 
 onError:{
	console.log(message); 
 } 
 onParametersUpdated:{
 //access them via parameters variable or getParameterValue call 
 } 
 timeout: 100000 
 loops: 1
 enabled: true 
}

**Comment by greenfield932** [comment]
I guess we can still keep direct calls (addParameter, requestConfig), it looks more usual for C++ code or if you write update logic yourself.

**Comment by Larpon** [comment]
@greenfield932 - Thanks for the feedback. When I started with QML on mobile all the AdMob and Analytics extensions/plugins where completely broken or only worked on one platform. So I tried having a go through Firebase :-)

You suggestions is exactly like what I had in mind - it's more QML declarative that way. I know it's extra work but it's more intuitive for QML-minded developers I think.

I guess we could use the automatic `onParametersChanged` signal that Qt will emit if you re-assign the `parameters` property?

I also thought we could let `parameters` be a type variant (`var`) Object - then people could access the parameters directly like in normal JavaScript objects? I'm not sure if it makes sense though:

```qml
RemoteConfig{
 parameters: {
	"TestString" : "test", 
	"TestDouble" : 2.56, 
	"TestLong" : 1100
 } 
 onError:{
	console.log(message); 
 } 
 onParametersChanged:{
 //access them via parameters variable
var test = parameters['TestString']
// or getParameterValue call 
 } 
 timeout: 100000 
 loops: 1
 enabled: true 
}
```
I'm not sure if it's a better way :-/ I can't remember right now why I made `userProperties` an array.

I agree we should definitely keep the direct calls.

What are the `loops` property for?
I'm asking because I haven't used the remote config API before - I guess you have a good reason :-)

**Comment by Larpon** [comment]
Then again a more QML-way would maybe be:
```qml
parameters: [
	RemoteConfigParameter { name: "TestString"; defaultValue: "test" }, 
	RemoteConfigParameter { name: "TestDouble"; defaultValue: 2.56 }, 
	RemoteConfigParameter { name: "TestLong"; defaultValue: 1100 }
 ]
```
- you know - having a type for the parameter list. You could reference the parameters by id in the code base like:
```qml
parameters: [
		RemoteConfigParameter { id: remoteConfigParam; name: "TestString"; defaultValue: "test" }, 
 ]
...
Item {
    someFeature: remoteCideasonfigParam.value
}
```
I might be over complicating things - Hmmm... Any thoughts?

**Comment by Larpon** [comment]
Oh! And good news: Your code runs flawlessly on iOS :-D

**Comment by greenfield932** [comment]
Great! 

I think loops is some overcomplicated thing, let's skipt it.
My initial idea about loops. The main purpose of remote config is to provide ability to change some parameters in firebase web console while your app installed on user's device can get these parameters remotely. When you change them on web console you want your app recieve them and change behaviour based on them. So the app can do update of the parameters in several ways: on startup or on every hour or on every 10 minutes and so on. Thus specifiyng loops parameter can set this logic, if loops==1 then it equals to request data once on startup. If loops==infinite then it equals request data on every time interval specified in timeout parameter. But for a single request like on startup it is enough to do it by manual call of requestConfig. Or we can specify some simple variable like requestOnce: true. What do you think?
Regarding parameters question I like this way
 onParametersChanged:{
    var test = parameters['TestString']
 } 
Let's keep it simple without dedicated type. I think we can access them from other items with this code 

Item {
    someFeature: remoteConfig.parameters['TestString']
}

**Comment by greenfield932** [comment]
Of course previously declaring remote config with id
RemoteConfig{
    id: remoteConfig
}

**Comment by Larpon** [comment]
You're right - it's too complicated with dedicated parameter type in this case.
Let's try this approach then:
```qml
onParametersChanged:{
   var test = parameters['TestString']
}
```
Regarding the `loops` and timer... Maybe it's easier to you let the user decide when it's time to poll for changes? Sorry I know I started the idea of integrating the timer :grin: 

I was thinking maybe people could just do:
```
RemoteConfig {
   id: remoteConfig

   Timer {
      running: remoteConfig.enabled
      repeat: true
      interval: 100000
      triggeredOnStart: true
      onTriggered: remoteConfig.poll()
   }

   parameters: {
	"TestString" : "test", 
	"TestDouble" : 2.56, 
	"TestLong" : 1100
    }

    onError:{
          console.log(message); 
    }

   onParametersChanged:{
      var test = parameters['TestString']
   }
   enabled: true // <- maybe keep this to prevent
}
```
Then poll is a public slot function which does the actual request etc. - and won't run if `remoteConfig.enabled == false`
Probably better to leave the polling to the user?

**Comment by Larpon** [comment]
Oh and the `long long cacheExpirationInSeconds` could be a property like `cacheExpiration` - and maybe made in milliseconds to adhere to QML standard timing values? (like `Timer.interval` etc.) - just do a validation on the value an make anything under 1000 equal to 1000? But this is nitpicking

**Comment by Larpon** [comment]
I can't see if we can omit the `ready` and `loaded` properties just yet but maybe they can be use on the C++ side to see what state everything is in...

**Comment by greenfield932** [comment]
Ok, let's make external timer. cacheExpiration as a property is also a good point.

**Comment by Larpon** [comment]
Sweet. I'll tag the project version 1.2 when we get this done. I've have been to eager to pull it in - as it might break a few user installs when we update it - I guess we can live with that :)

**Pull request merged**
