### PR TITLE
qtfirebase.cpp:49:18: error: 'class firebase::FutureBase' has no memb…

### PR DESCRIPTION
**Pull request by CMGeorge**
…er named 'status'

     while(future.status() == firebase::kFutureStatusPending) {....

### CODE REVIEW

**Comment by greenfield932** [comment]
It seems you are on the firebase old versions. In my header of firebase 3.1 I see two definitions, the
capital letter version marked as deprecated.

FIREBASE_DEPRECATED FutureStatus Status() const { return status(); } 
FutureStatus status() const;

**Comment by Larpon** [comment]
@CMGeorge - with current master branch and/or release [v1.2](https://github.com/Larpon/QtFirebase/releases/tag/v1.2) - you shouldn't encounter these problems if you run off the latest Firebase C++ SDK? (3.1.0 last time I checked)

**Comment by Larpon** [comment]
@CMGeorge - I fixed them in [this commit]?(https://github.com/Larpon/QtFirebase/commit/2b40cf55b9ef09b71ef268b7d3194f2fe0bdc142)

**Comment by Larpon** [comment]
@CMGeorge - thanks for contributing. I'm closing this for now though as your changes has been dealt with in newer commits. Sorry if this breaks anything for you. You are welcome to open an issue if you for some reason need to be use the Firebase C++ SDK 2.x versions

**Pull request closed without merging**
