### PR TITLE
Update remote config wrapper API to fit QML code better

### PR DESCRIPTION
**Pull request by greenfield932**
Update RemoteConfig class to fit QML better. Added "parameters" and "cacheExpirationTime" variable in milliseconds. Removed "loaded" variables and signals. Updated example code in the class header.

### CODE REVIEW

**Comment by Larpon** [comment]
Man this is awesome - thank you - I'll hopefully have time to merge and iOS test tomorrow!

**Comment by greenfield932** [comment]
Thanks! It would be great!

**Comment by Larpon** [comment]
QtFirebase v1.2 is now officially out including all this. 
:champagne: :fireworks:

I've done a quick test with iOS and it seem to run fine.

**Comment by greenfield932** [comment]
Cool!

**Pull request merged**
